### ISSUE TITLE
test on my dataset

### ISSUE THREAD

**Issue by LaiXiansong** [FENGGENYU/CAPRI-Net#4]
Thanks for your excellent work. 
I'm trying to run your code on my data.
I made one voxel sample. The 4th row in "voxel2mesh["points"]" is not correct but "voxel2mesh["points"]" is right. I ran "fine_tuning.py" and the results were:
```python
......
CAPRI - DEBUG - epoch = 2609/2630 err_left = 0.000000, err_right = 0.000000, total_loss=0.000000, 1 epoch time =0.422172, left tim
e=0.147760                                                                                                                                                                   
CAPRI - DEBUG - epoch = 2619/2630 err_left = 0.000000, err_right = 0.000000, total_loss=0.000000, 1 epoch time =0.416848, left tim
e=0.076422                                                                                                                                                                   
CAPRI - DEBUG - epoch = 2629/2630 err_left = 0.000000, err_right = 0.000000, total_loss=0.000000, 1 epoch time =0.415986, left tim
e=0.006933                                                                                                                                                                   
stage time:,  84.60717487335205  
```

Then I ran "test.py" and it raised: 
```python
Traceback (most recent call last):
  File "test.py", line 205, in <module>
    inter_results_flag = True, final_result_flag = True
  File "/data1/lxs/myproject/CAPRI-Net/utils/cad_meshing.py", line 177, in create_cad_mesh
    primitives, N, c_dim, threshold = sampling_threshold)
  File "/data1/lxs/myproject/CAPRI-Net/utils/cad_meshing.py", line 117, in sample_points_around_estimated_surface
    points, _ = mesh.sample(50000, return_index=True)
  File "/home/laixs/miniconda3/envs/py37/lib/python3.7/site-packages/trimesh/base.py", line 2312, in sample
    mesh=self, count=count, face_weight=face_weight)
  File "/home/laixs/miniconda3/envs/py37/lib/python3.7/site-packages/trimesh/sample.py", line 55, in sample_surface
    face_pick = np.random.random(count) * weight_cum[-1]
IndexError: index -1 is out of bounds for axis 0 with size 0
```

Do I need to set the "points" data in "voxel2mesh.hdf5" correctly to get the correct result?
Thanks.

**Comment by FENGGENYU** [comment]
It looks your data is wrong, the loss won't be 0.

You need to make both voxels and points are right.

You can follow this code to sample voxels and points:

https://github.com/jchibane/if-net/tree/master/data_processing

**Comment by LaiXiansong** [comment]
Thank you, but I am still very confused about points sampling. From the data set visualization results, points are randomly sampled in the 64 * 64 * 64 space, and those that belong to the part will be marked as 1. But this new 64 * 64 * 64 The grid is inconsistent with the original grid scale, and it can be seen from the figure that it has been stretched. I don't know what this part does. Can you provide the code for data pre-processing, or tell me which script you used in if-net ("voxelized_pointcloud_sampling.py" or "boundary_sampling.py") ? 
![Screenshot 2022-12-08 185225](https://user-images.githubusercontent.com/53077787/206428981-4aac86f2-cefb-4bbf-b8d1-88569857090b.png)
